Profile page picture, bio, details, and users post added in the page
rekesan/facebook-clone pull request #3
Opened 2023-03-09 08:12 UTC by rekesan

2023-03-09 08:14 UTC, jendan-nikolai commented on app/Login.tsx
> +    console.log(await AsyncStorage.getItem("username"))
remove unnecessary code

2023-03-09 08:16 UTC, jendan-nikolai commented on app/profile/[userId].tsx
> +const getUser = async (p: { uName?: string; id?: number | string }) => {
be specific with the naming

2023-03-09 08:18 UTC, jendan-nikolai requested changes
be specific in naming variables and remove unused codes

2023-03-09 08:21 UTC, jendan-nikolai commented on app/_layout.tsx
> +          headerShown: route.name.includes("profile") ? true : false,
remove ternary condition

2023-03-09 08:23 UTC, jendan-nikolai commented on app/profile/[userId].tsx
> +  if (userId === "me") {
avoid using abbreviations in variable names

2023-03-09 10:11 UTC, mika-ella commented on service/data.tsx
> +export const mockDetails = [
create types for this

2023-03-09 10:11 UTC, mika-ella commented on app/profile/[userId].tsx
> +  } catch (e) {
rename, what's the variabale e?

2023-03-09 10:11 UTC, mika-ella commented on app/Login.tsx
> +  } catch (e) {
change variable name

2023-03-09 11:32 UTC, mika-ella commented on app/profile/[userId].tsx
> +    (user) => user.username === props.username || user.id == props.id
add type for user

2023-03-09 11:32 UTC, mika-ella commented on app/profile/[userId].tsx
> +const getUserData = async (props: {
do not use props as a variable name, use an interface, might be userDTO

2023-03-09 11:32 UTC, mika-ella commented on app/profile/[userId].tsx
> +  const mainButtonStyle = sx({
rename, should be named based on its use

2023-03-09 11:32 UTC, mika-ella commented on app/profile/[userId].tsx
> +  const secondButtonStyle = sx({
do not use numbers to define a style

2023-03-09 11:32 UTC, mika-ella commented on app/profile/[userId].tsx
> +  const thirdButtonStyle = sx({
do not use numbers to define a style

2023-03-09 12:26 UTC, mika-ella approved these changes

2023-03-10 00:32 UTC, jendan-nikolai approved these changes

2023-03-10 00:37 UTC, merged